modLoader="javafml"
loaderVersion="[47,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="soul_knife"
version="1.0.0"
displayName="Soul Knife"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="36101, MCreator"
description="Adds a soul knife whose damage increases as you kill mobs with it!"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.soul_knife]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



